"""chapter on manhwa

Revision ID: 0171f387cb53
Revises: 62f378b5370d
Create Date: 2023-11-21 12:28:57.820844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0171f387cb53'
down_revision: Union[str, None] = '62f378b5370d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('manhwa_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['manhwa_id'], ['manhwa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_id'), 'chapter', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chapter_id'), table_name='chapter')
    op.drop_table('chapter')
    # ### end Alembic commands ###
