"""drop column

Revision ID: 5bcd80320a45
Revises: 76fa791d7552
Create Date: 2023-11-14 10:10:53.342168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bcd80320a45'
down_revision: Union[str, None] = '76fa791d7552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('manhwa') as batch_op:
        batch_op.drop_column('artist')
        batch_op.drop_column('author')

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manhwa', sa.Column('artist', sa.VARCHAR(), nullable=True))
    op.add_column('manhwa', sa.Column('author', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
