"""drop column genero

Revision ID: 62f378b5370d
Revises: fe33b8a1b2f5
Create Date: 2023-11-21 11:54:42.512201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f378b5370d'
down_revision: Union[str, None] = 'fe33b8a1b2f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_genero_id', table_name='genero')
    op.drop_table('genero')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genero',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name_gender', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_genero_id', 'genero', ['id'], unique=False)
    # ### end Alembic commands ###
