"""add update

Revision ID: 76fa791d7552
Revises: e86a28cf1f7f
Create Date: 2023-11-07 16:12:20.724380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76fa791d7552'
down_revision: Union[str, None] = 'e86a28cf1f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manhwa', sa.Column('update_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manhwa', 'update_at')
    # ### end Alembic commands ###
