"""add column type_book

Revision ID: e86a28cf1f7f
Revises: 4637b0938ec5
Create Date: 2023-10-24 09:03:48.146118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86a28cf1f7f'
down_revision: Union[str, None] = '4637b0938ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manhwa', sa.Column('type_book', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manhwa', 'type_book')
    # ### end Alembic commands ###
